apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecanvas.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubecanvas.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kubecanvas.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
