{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecanvas.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubecanvas.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-account
{{- end }}
